services:
  postgres:
    image: postgres:16
    container_name: ecom-micro-postgres
    environment:
      POSTGRES_DB: ecom_micro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
